# Created by: Peter Birksmith
# Application owner: Data Quality Team
#
- name: Install ASCI ActiveBatch Automation Agent
  hosts: asci_prod
  become: yes
  become_user: root

  vars:
     abatagent_dir: /opt/ASCI
     activebatchv11_dir: /ActiveBatchV11
     activebatchv11_ver: Linux-11.0-v11_x3264
     asci_ver: 11.0
     tmp_dir: /tmp

# Nexus Repository URL
     nexus_url: ../nexus/service/local/repositories/thirdparty/content/com
#
# Activebatch Agent
     asci_agent_url: '{{ nexus_url }}/Activebatch/ActiveBatch_Linux/{{ asci_ver }}/ActiveBatch_Linux-11.0-v11_x3264_linux.tar'

  tasks:
   - name: create Asci software directory /opt/ASCI
     file: 
       path: '{{ abatagent_dir }}'
       state: directory 
       mode: 0755

   - name: create Asci software directory /opt/ASCI/ActiveBatchV11
     file: 
       path: '{{ abatagent_dir }}{{ activebatchv11_dir }}'
       state: directory 
       mode: 0755

   - name: Download AB11 tar file
     get_url: 
       url: '{{ asci_agent_url }}'
       dest: '{{ tmp_dir }}/ActiveBatch_{{ activebatchv11_ver }}_linux.tar'

   - name: Unzip AB11 Install zip
     unarchive:
       src:  '{{ tmp_dir }}/ActiveBatch_{{ activebatchv11_ver }}_linux.tar'
       dest: '{{ abatagent_dir }}{{ activebatchv11_dir }}'
       remote_src: yes

   - name: Silent install of AB11
     command: ./abatinstall -s -d {{ abatagent_dir }}{{ activebatchv11_dir }}
     args:
       chdir: '{{ abatagent_dir }}{{ activebatchv11_dir }}/'
     become: yes
     become_user: root

# AbatEmgr.Conf
   - name: Configure ASCI configuration
     template:
       src: AbatEmgr.Conf.j2
       dest: '{{ abatagent_dir }}{{ activebatchv11_dir }}/AbatEmgr.Conf'

   - name: Run AB11 configuration
     command: ./abatstartup -g -f {{ abatagent_dir }}{{ activebatchv11_dir }}/AbatEmgr.Conf
     args:
       chdir: '{{ abatagent_dir }}{{ activebatchv11_dir }}/ActiveBatchV11/bin/' 
     become: yes
     become_user: root

# Check Abat status
   - name: Check AB11 Status
     command: ./abatstatus
     args:
       chdir: '{{ abatagent_dir }}{{ activebatchv11_dir }}/ActiveBatchV11/bin/'
     become: yes
     become_user: root 
