# Created by: Peter Birksmith
# Application owner: Data Quality Team
#
- name: Copy talend Software to JobServer
  hosts: nginx_prod
  become: yes
  become_user: root

  vars:
     nginx_dir: /etc/nginx
     www_dir: /data/www
     img_dir: /images
     script_dir: /scripts
     media_dir: /media
     
     test1_user: test1user
     test2_user: test2user
     test3_user: test3user
     test_pwd: test123

     test1_group: test1group
     test2_group: test2group

  tasks:
   - name: Install web server
     yum: 
       name: '{{ item }}'
       state: latest
     with_items:
     - git
     - npm
     - htop
     - tmux
     - nodejs
     - jake
     - nginx

   - name: Create test1 group
     group: 
       name: '{{ test1_group }}'

   - name: Create test2 group
     group: 
       name: '{{ test2_group }}'

   - name: create test1 user
     user: 
       name: '{{ test1_user }}'
       password: '{{ test_pwd }}'
       group: '{{ test1_group }}'
       groups: '{{ test1_group }},{{ test2_group }},wheel'
       append: yes

   - name: create test2 user
     user: 
       name: '{{ test2_user }}'
       password: '{{ test_pwd }}'
       group: '{{ test2_group }}'
       groups: '{{ test2_group }},wheel'
       append: yes

   - name: create test3 user
     user: 
       name: '{{ test3_user }}'
       password: '{{ test_pwd }}'
       group: '{{ test2_group }}'
       groups: '{{ test3_group }},wheel'
       append: yes

   - name: create nginx directory /data/www
     file: 
       path: '{{ www_dir }}'
       state: directory 
       mode: 0755

   - name: create nginx directory /data/www/image
     file: 
       path: '{{ www_dir }}{{ img_dir }}'
       state: directory 
       mode: 0755

   - name: create nginx directory /data/www/scripts
     file: 
       path: '{{ www_dir }}{{ script_dir }}'
       state: directory 
       mode: 0755

   - name: create nginx directory /data/www/media
     file: 
       path: '{{ www_dir }}{{ media_dir }}'
       state: directory 
       mode: 0755

   - name: create nginx directory /data/www/test1
     file: 
       path: '{{ www_dir }}/test1'
       state: directory 
       mode: 0755
       group: '{{ test1_group }}'

   - name: create nginx directory /data/www/test2
     file: 
       path: '{{ www_dir }}/test2'
       state: directory 
       mode: 0755
       group: '{{ test2_group }}'

   - name: create nginx directory /data/www/test3
     file: 
       path: '{{ www_dir }}/test3'
       state: directory 
       mode: 0755 

   - name: Copy nginx conf file
     template:
       src: nginx.conf.j2
       dest: '{{ nginx_dir }}/nginx.conf'

   - name: Copy nginx .htpasswd file
     template:
       src: .htpasswd.j2
       dest: '{{ nginx_dir }}/.htpasswd'

   - name: Copy index html file
     template:
       src: index.html.j2
       dest: '{{ www_dir }}/test1/index.html'

   - name: Copy index html file
     template:
       src: index.html.j2
       dest: '{{ www_dir }}/test2/index.html'

   - name: Copy index html file
     template:
       src: index.html.j2
       dest: '{{ www_dir }}/test3/index.html'

   - name: Reload Configuration
     command: nginx -s reload
